### ISSUE TITLE
Hello, I'm Leo and I look forward to meeting you all :))

### ISSUE THREAD

**Issue by leochoi2002** [TheBreakingGoodProject/Dalyell-Projects#3]
Hey guys,
I'm Leo, a first year student studying Bsc/MD. I'm majoring in Anatomy & Histology + Immunology & Pathology and I really look forward to starting this program with you guys. I joined this project (partially because I was late in choosing) to get a greater understanding of how people interact with medical information online. 

Especially with the recent COVID-19 pandemic, I feel that people are increasingly exposed to a lot of misinformation on the web regarding diseases and medicines. To address this, I believe that educating people in how to research safely online would be of paramount importance, and worth investing time and resource into. Of course google can never replace your MD (haha), but in all seriousness, I believe that a greater job can be done in educating people on how to go about accessing the correct information online.

Keen to meet the group 😄

**Comment by leochoi2002** [comment]
Date: 20/03/21 [Sat]

I completed Challenge #1, and I am currently finding the project quite enjoyable. In addition to my current love for the field of medicine, I now have the chance to research it, so I feel that this is a great opportunity for me to learn more about essential medicines and the medical field. For the challenge, I started looking into the drug Remdesivir, a drug used to increase recovery time in COVID-19 patients. I realised that I had heard about the drug quite often from the internet, due to ex-President Trump receiving a 5-day course of this drug when he had the virus. An interesting thing that I found was how this was likely to misinform the public about the effectiveness of this medicine. Due to a powerful world figure receiving the drug, people may be likely to believe in the effectiveness of the drug, despite a randomised global trial leading to the World Health Organisation (WHO) concluding that it has “little to no effect on hospitalised patients with COVID-19” [1]. Finding out that one in two Americans were still receiving this drug, I feel that more work needs to be done in providing the correct science and recommendations to the public.

Websites visited today:
[1] https://www.nytimes.com/interactive/2020/science/coronavirus-drugs-treatments.html

**Comment by leochoi2002** [comment]
Date: 24/03/21 [Wed]

As I start Challenge #2, I learnt a useful piece of information in researching the web, in that .org websites are generally trustworthy. Because I only knew about .gov and .edu being generally trustworthy websites, I now feel that more can be done to inform the public about how to better identify trustworthy websites to educate themselves with.

Another thing that I have newly discovered is that the - (minus) symbol can remove certain keywords from being searched in Google. I feel that this was another useful piece of information I learnt in improving my ability to research.

Despite having some difficulties finding the price hikes, I found that the project did a great job in guiding me to the correct website (which I had stumbled upon before too), and explained how to interpret values such as the DPMQ. However, the one part of this challenge which I disliked was that the project showed no guide on to find the price difference. I found that it only allowed us to view the current price per unit (assuming maximum units), over any kind of price difference. I feel that the project would benefit from incorporating some kind of guide in finding the price difference.

One final thing which I would add is that the entire process was not enjoyable at all. By adding a gamified interface or a more dynamic colour scheme, I feel that more people would be engaged in completing these Challenges.

**Comment by leochoi2002** [comment]
Date: 27/03/21 (Sat) [Apologies for the late upload onto Github]

As I start Challenge #3, I found that I started to understand better about how pharmaceutical companies operate, where drugs are made and sold not just to consumers, but between different companies as well. I particularly enjoyed the example flowchart demonstrated when I entered the website for Challenge #3. However, I have to again critique the poor design choice of the website which makes the writing not only difficult to read, but also difficult to engage with.

In terms of research though, I felt that the website did a fairly decent job at explaining which steps to follow in order to find, for example, the company holding the rights for a drug such as ribavirin. However, there was a bit of conflicting information from the previous Challenges, which suggested to me to use an .au website to get information specific to Australia, where Challenge #3 suggested we use information from the FDA.

Medicine 2: Carbetocin

Challenge #1
Whilst doing some research on carbetocin, I learnt that it was a “synthetic analogue of oxytocin, with a longer half-life”[2].

As I make my way through Challenge #1 again with Carbetocin, I found that when side effects such as nausea and vomiting occur upon the administration of the drug, actions to be taken in this context are quite vague. The only information I could really find was to seek medical attention from doctors, and that these symptoms would likely fade away as your body adapts to the administered carbetocin[3]. 

[2] (2021). Retrieved 27 March 2021, from https://www.nps.org.au/australian-prescriber/articles/carbetocin
[3] (2021). Retrieved 27 March 2021, from https://www.nps.org.au/australian-prescriber/articles/carbetocin

**Comment by leochoi2002** [comment]
Date: 29/03/21 (Mon)

Challenge #2:
We encountered a problem in Challenge #2, which was that it did not contain the second medicine I chose (carbetocin). Hence, I decided to go with dapsone as my medicine for Challenge #2. 

Update: Different link was provided to the participants of the project which contained carbetocin and the other medicines listed on Github.

Challenge #2 (this time with carbetocin):
Whilst I could not find any information to do with the price hike, I found some other relevant information which was intriguing to me. 

As I found out that carbetocin is a drug which can be used to prevent Postpartum Hemorrhage (PPH)[4], I began to research more into how it compared with drugs such as oxytocin which also served a similar purpose. I found that whilst carbetocin “costs 20 times more than oxytocin”[4], it has an advantage over oxytocin in middle to lower income countries due to being heat-stable, whereas oxytocin must be stored and transported at cold temperatures. This would help explain why both oxytocin and carbetocin are in the Essential Medicines List by the World Health Organisation (WHO)[5]. 

Another thing to note was that carbetocin was not listed on the Australian Pharmaceutical Benefits Scheme (PBS)

[4] Gallos, I. D., & Coomarasamy, A. (2019). Carbetocin: Worth the extra expense?. Best practice & research. Clinical obstetrics & gynaecology, 61, 55–65. https://doi.org/10.1016/j.bpobgyn.2019.04.001
[5] Carbetocin - EML. (2021). Retrieved 29 March 2021, from https://www.who.int/selection_medicines/committees/expert/22/applications/carbetocin/en/

Challenge #3
From Challenge #2, I came across a pdf file from the Therapeutic Goods Administration (TGA), which gave me the information on the company which holds the rights to carbetocin. This was found to be Ferring Pharmaceuticals Pty Ltd. which branded the substance as Duratocin[6]. 

[6] Therapeutic Goods Administration. (2018, August). Australian Public Assessment Report for Carbetocin. https://www.tga.gov.au/sites/default/files/auspar-carbetocin-180823.pdf

Overall after completing the set of challenges for carbetocin, I feel that my research skills have improved, as evident to my deeper understanding of the purpose of the drug, as well as its cost-benefit analysis when compared to a similar drug such as the hormone, oxytocin. I also feel more confident in my research abilities. However, what I do feel, is that due to my research abilities improving, I am spending more time researching information about the drug that is outside the scope of the challenges.

**Comment by leochoi2002** [comment]
Date: 30/03/21

Medicine 3: Digoxin

Researching digoxin before I attempt Challenge #1, I found a few pieces of interesting information. First is that it is a “relatively safe, cheap and effective therapy” for congestive heart failure[7]. It works via slowing your heart rate and making the heart beat stronger instead[8]. I am also finding research a lot easier than it was at the start of the project. However, in terms of citizen science, I believe it would be unfeasible to have an ordinary citizen so this research process 5 times, whereas we are full time students doing the Dalyell project.

[7] Australian Prescriber. (1999, December). Digoxin in the 21st century. https://doi.org/10.18773/austprescr.1999.123
[8] NHS website. (2020, March 10). Digoxin. Nhs.Uk. https://www.nhs.uk/medicines/digoxin/

Challenge #1 & Challenge #2
Using my improved set of researching skills, I was able to find a website on the price hike of digoxin rather quickly.

One website reported that the price increased from $1.15 US for 3 month supply to $30 US a month[9]. 

Interestingly enough, the first and second challenge aligned with the task of finding price hikes. When I tried to look into whether other countries were affected by this price hike, I couldn’t find any information on how the price hike in the US has affected other countries in the past, however, I found that the global digoxin market was expected to increase exponentially during 2028[10]. The reason why this was the case could not be obtained, for the website required me to purchase their report.

Reasons as to why prices of generic drugs such as digoxin were going up were found to be mostly because of 2 main factors: One being that there were “reduced competition due consolidation in the industry” and two, that “market and regulatory faces [...] altered incentives for firms producing generic drugs”.[11]

[9] Lawyers look at new price hike for old drug / General / Generics / Home - GaBI Online - Generics and Biosimilars Initiative. (2014). GaBI Online. https://www.gabionline.net/Generics/General/Lawyers-look-at-new-price-hike-for-old-drug
[10] A. (2020, December 21). Global Digoxin Market to Increase Exponentially During 2028: Lexis Business Insights Latest Updates. The Courier. https://www.mccourier.com/global-digoxin-market-to-increase-exponentially-during-2028-lexis-business-insights-latest-updates/
[11] Joyce, G. (2015, January 21). Why are some generic drugs getting so expensive? The Conversation. https://theconversation.com/why-are-some-generic-drugs-getting-so-expensive-35603

**Comment by leochoi2002** [comment]
Date: 31/03/21 (Wed) [Apologies for the late upload onto Github]
Challenge #3 Continued:
There’s a bit of confusion between whether digoxin should be treated as a generic drug, since I found that it was both approved under a brand name (Lanoxin) in 1997, as well as approved as a generic drug multiple times for companies other than Glaxo Wellcome.[13]

[13] Drug Approval Package: Lanoxin NDA 20405. (1997). Lanoxin. https://www.accessdata.fda.gov/drugsatfda_docs/nda/97/020405_lanoxin_toc.cfm

Reflection
Observing that the amount of time taken to research is progressively decreasing, I believe that the project has been to some extent successful in improving my ability to research online. However, I would like to once again mention the lack of cohesiveness in the project. I personally found no specific purpose as to why we are completing this project aside from increasing our ability to investigate medical information online. If the project were to provide drugs that are specifically relevant to our personal lives, as well as the current affairs of the world, I feel that the project would be more worthwhile completing for the participants of the future who may not be students like we are. Examples would be drugs related to the current pandemic that people would want to understand.

Medicine 4: Warfarin

Warfarin is a prescription medicine which is used to prevent blood clots forming, as it is an anticoagulant which has been used for many decades.[14]

[14] Warfarin & how to take it. (2020, December 9). NPS MedicineWise. https://www.nps.org.au/consumers/warfarin#what-is-warfarin?


Challenge #1
During Challenge #1, I am trying to attempt to find some clinical trial results for warfarin, since for the other medicines, I have not attempted to find any kind of trial results. Thus, I stumbled upon an article that related the use of warfarin in osteoarthritis patients, with the risk of knee and hip replacements[15]. This was really interesting to me as no studies “to date have evaluated whether [...] warfarin, an anticoagulant drug, can be detrimental to OA”[15]. New medical studies are being published everyday, and I feel quite excited to understand how much of an evolving field medicine is. I also came to understand how people can benefit from learning researching skills, as they would then have the ability to educate themselves before falling victim to misinformation online.

[15] Staff, S. X. (2020, November 6). Warfarin use significantly increases risk of knee and hip replacement in people with OA. Warfarin Use Significantly Increases Risk of Knee and Hip Replacement in People with OA. https://medicalxpress.com/news/2020-11-warfarin-significantly-knee-hip-people.html

Challenge #2
After some time trying to find a price hike for warfarin, I could only find some vague information of the increase in the cost of warfarin: “from a few dollars per tablet to more than $60”[16]. This source[16] also revealed how warfarin tablets were part of a major issue in the pharmaceutical industry, which was that there was not enough competition to keep prices of brand, and even generic drugs modest.

[16] Dennis, B., Dennis, B., & Dennis, B. (2016, March 14). Rattled by drug price increases, hospitals seek ways to stay on guard. Washington Post. https://www.washingtonpost.com/national/health-science/rattled-by-drug-price-increases-hospitals-seek-ways-to-stay-on-guard/2016/03/13/1c593dea-c8f3-11e5-88ff-e2d1b4289c2f_story.html



Challenge #3
After digging through the record of the US Foods and Drug Administration (FDA), I found that the first owner of warfarin was Bristol Myers Squibb[17], where it was approved in 1954. I would also like to note how routine researching medicines have become at this point. Compared to my frustrations earlier on during the project, I feel more in control of the direction of my research.

[17] Drugs@FDA: FDA-Approved Drugs. (n.d.). FDA. Retrieved March 31, 2021, from https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&varApplNo=009218

**Comment by leochoi2002** [comment]
Date: 01/04/21 (Thurs)

Challenge #3 cont.
Whilst browsing the internet, I stumbled upon an article that stated that warfarin was found by a large study in 2017 to be not as effective as newer direct oral anticoagulants (DOACs)[18]. 

[18] Curley, B. C. (n.d.). ERROR: The request could not be satisfied. These Blood Thinners May Be Better Option Than Warfarin for People with AFib. Retrieved April 1, 2021, from https://www.healthline.com/health-news/these-blood-thinners-may-be-better-option-than-warfarin-for-people-with-afib

Reflection
After completing the set of challenges for the fourth time, I am relieved at the fact that I have continued to improve my skills in research, where I now understand which keywords to type in order to retrieve the information. An example would be how instead of trying to find specific events for the medicine, I would rather type “<name of medicine> news”. Overall though, I feel that this project is becoming too repetitive.


Medicine 5: Rifabutin

A quick google search online found that Rifabutin was an antibiotic used to treat Mycobacterium avium complex disease (MAC) in patients with a HIV infection.[19]

[19] Rifabutin: MedlinePlus Drug Information. (n.d.). Rifabutin. Retrieved April 1, 2021, from https://medlineplus.gov/druginfo/meds/a693009.html




Challenge #1 & 2
After surfing the web, I could not find a specific price change in the drug, however, I did find that “rifabutin has been recognised in 2009 as an Essential Medicine according to the WHO [... and] is no longer protected by patent and its price has been reduced by 60%”[20].

[20] Crabol, Y., Catherinot, E., Veziris, N., Jullien, V., & Lortholary, O. (2016, March 23). Rifabutin: where do we stand in 2016? OUP Academic. https://academic.oup.com/jac/article/71/7/1759/1750373

Overall, the first two challenges were completed quite swiftly and there were not too many problems in completing the research required.

Challenge #3
Whilst researching who the first owner of rifabutin was, I found that Archifar, an Italian drug company discovered it in 1975[21]. This was an interesting discovery, since all the research on these essential medicines done by me were mostly related to the US/Australia as information were mostly sourced from Australian websites or the FDA. This made me understand the global nature of  pharmaceuticals that is not only limited to one or two countries.

By using the “news” column in Google, I was able to quickly identify research done regarding rifabutin, where results suggest that it is “highly active in fighting multidrug-resistant Acinetobacter baumannii”[22]. 

[21] Rifabutin | Working Group for New TB Drugs. (n.d.). Rifabutin. Retrieved April 1, 2021, from https://www.newtbdrugs.org/pipeline/compound/rifabutin
[22] Press Release. (2020, June 9). TB drug, rifabutin, active against Acinetobacter baumannii in the lab. Outbreak News Today. http://outbreaknewstoday.com/tb-drug-rifabutin-active-against-acinetobacter-baumannii-in-the-lab-17639/

Reflection
After completing 5 sets of Challenges #1~3, I have come to understand the rigorous process of researching, and begun to believe in the importance of the skill of researching in one’s daily life. An example of this might be the misinformation spread around during the current global pandemic, where projects such as this one could be useful in educating people to do their own research on trustworthy websites such as .edu, .gov, and .org websites. In terms of the improvement of my own understanding of research, I feel that the most important piece of skill that I acquired during this project was how to identify the keywords to include during my search for specific information on the web. Finally, my ability and understanding on how to, and why we must cite our sources have undoubtedly improved as I had to cite up to 22 different sources during the course of this project.

**Comment by amychau16** [comment]
Hi Leo!

After reading through your journey, I saw some of your frustrations with this project that weren't necessarily what I had thought of when I was reflecting on my learning experience. However, after seeing this in retrospect, I do agree that these were definitely some good points that we should keep in mind.

- I could tell that you came into this project with a great sense of interest (which was me as well), however as you got to know the challenge process, you did find some aspects not very enjoyable. You mentioned that changing the interface of the challenge website could be a possible recommendation, which I agree with. I also think that if the design was more pleasing to the eye and interactive, participants would be more engaged throughout the research process.


> **However, what I do feel, is that due to my research abilities improving, I am spending more time researching information about the drug that is outside the scope of the challenges.**

- I also resonated with how the challenge allowed me to further develop my inquiry/research skills which meant I was spending a lot of time researching things beyond the scope of the challenges (although I did this even before I was used to the challenge process as I spent time reading through many sources before I found relevant information).
While I do think that researching beyond the scope of the challenges is a positive outcome as the participant could be learning more about a medication or gaining interest in an area that they never thought they would be, there are some downfalls to this. For participants that may have less interest in medicines or motivation, they would find this process redundant, time-consuming, and frustrating especially when they see that there is no benefit to this process for themselves.


> **I am also finding research a lot easier than it was at the start of the project. However, in terms of citizen science, I believe it would be unfeasible to have an ordinary citizen do this research process 5 times, whereas we are full time students doing the Dalyell project.**

- Correct me if I am wrong, but I think in this part of your journal, you have pointed out a problem associated with staying motivated to continue repeating this challenge 5 times. 
 I do think that because we are participating in this challenge as full-time Dalyell students, this is one of our motivators that is sustaining our participation.  I do agree that an ordinary participant may not have the same level of motivation especially if they do not have pre-existing interest in medicines, or if they do not see a real benefit of this challenge for themselves. 

That's why I think you brought up a really good point afterwards:

> **However, I would like to once again mention the lack of cohesiveness in the project. I personally found no specific purpose as to why we are completing this project aside from increasing our ability to investigate medical information online. If the project were to provide drugs that are specifically relevant to our personal lives, as well as the current affairs of the world, I feel that the project would be more worthwhile completing for the participants of the future who may not be students like we are...**

If having motivation to continue active participation is dependent on an individual's interests, I think that expanding the list of essential medicines could be a good idea to engage people who will be motivated if they see a medicine that is relevant to their own health and context.

I did find that my purpose in doing this project did become somewhat muddled as I was completing the challenges. Although I knew that gathering information was all part of helping with research, if I was an ordinary participant and I did not exactly know the potential outcomes of my input, I would become very lost with the project's purpose -- probably something to keep in mind.

**Comment by ShirleyZ11** [comment]
Hi Leo,

Thank you for sharing your learning experiences. I found it interesting to read about your thoughts regarding the project and noticed that like others, we faced similar challenges throughout the process. 

After reading all your journal entries, it made me consider some problems that actually weren't that apparent to me initially, but now are issues I can emphasise with as well. Key things that stood out to me, was when you mentioned the repetitive nature of the task and how the purpose of completing these became lost. For me, I came to appreciate the repetition of the challenges as something that allowed me to expand on my research skills- because the tasks became more familiar, I was able to focus on the way I was researching. The purpose of the challenges, I think, would be slightly different to the general public who are participating. As Dalyell students, our goal was to uncover the learning processes that occurred whilst completing these challenges, and hence perhaps it was less about personal interest with the challenges, but more about active participation with this unit of study as a whole. It would be interesting to consider how one's motivations can affect their participation and experience with the challenges.

I found your entries very insightful, and in some ways, showed me a different perspective to the task than I previously had. You made me reconsider much about the challenge, and this just shows how one task can yield such different experiences and outcomes. I'm looking forward to working as a team now for Task 3 to bring all the ideas together!

**Comment by mnie6637** [comment]
Hey Leo! 
Thanks for your entries on your research process, it's easy to see that you have a great deal of personal interest in medicine, which is awesome! :)

Looking at your News Flash challenges, I think we both resonated with the idea that media greatly influences the science available and accessible to the public, and hence their opinions on different medicines. 

You mentioned that you discovered .org websites were generally trustworthy, and to an extent I agree; in my experience I definitely found that some .org websites were severely outdated and without any references/sources to show their reliability. 

I also found using the "- (minus) symbol", as well as quotation marks and some other search features to be really useful, and I believe future participants would benefit from having more information on how to use them.

Just like you did, I found it hard to find all the price differences, as the majority of the information available online relies on journalism, which might not be present for some medicines. Some sort of guide to searching for information, maybe specifically from certain text types (eg. Online news/reports) could aid the process?

Just like everyone else has mentioned, a neater/more vibrant interface would greatly help with user friendliness and the desire to complete the challenges. While not part of the research process itself, it would definitely improve the outcomes of the project. I really liked your idea of adding a 'gamified interface', I thought the idea of making it more game-like rather than survey-like could improve interest a lot.

You mentioned "there was a bit of conflicting information from the previous Challenges [...]". I definitely found this to be the case too, and I think this problem relates back to the user-friendliness of the project. Some of the questions could be revised to be more specific, and other questions added to encompass all the information we find, so we don't have to be as selective when all the information we find can be useful.

I really resonated with how you felt you were researching outside of the scope of the challenges, and that often the information you found wasn't relevant. With my experiences, I was really interested in how this could lead to some form of cognitive overload, and be detrimental to the research process. Or alternatively, how the extra information and the wide learning achieved as a result could be more beneficial in terms of the participants' individual knowledge base beyond the project outcomes. I think Amy summed these up well in her comment above.

I'm curious as to how exactly your research skills have improved as you went through the challenges? I also found that my research became faster as the challenges went on, and it's hard to pinpoint exactly where this efficiency came from (using proper keywords, for example). I was also interested in your analysis of the motivations of participants. While I think that improving one's ability to do medical research is actually an important outcome of the project, I do understand your feelings that there may not be a sense of personal relevancy while researching these drugs. Would having a brief description of the drug presented to participants before they begin research help them choose ones that would interest them?
